name: tao_cat
description: "An awoken cat that helps translate."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_list_view: ^1.1.26
  provider: ^6.1.2
  yaru: ^5.3.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
